InternAssignment/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
]

urlpatterns += staticfiles_urlpatterns()

index/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'index'
urlpatterns = [
    path('signup',views.sign_up,name = 'signup'),
    path('login',views.login_view,name = 'login'),
    path('home/<slug:user_id>',views.home,name = 'home'),
    path('logout',views.logout_view,name = 'logout'),
    path('additem',views.additem_view,name = 'additem'),
    path('update/<slug:item_id>',views.update_view,name = 'updateitem'),
    path('filter/', views.filter_view, name="filter"),
    path('delete/<slug:item_id>', views.delete_view, name="delete"),
    path('edit/<slug:item_id>', views.edit,name="edit"),
]

index/models.py
from django.db import models
# Create your models here.

class itemmodel(models.Model) :

    userid = models.CharField(max_length = 100)
    name = models.CharField(max_length=300)
    quantity = models.CharField(max_length=400)
    date = models.DateField(default="04-09-2021")
    status = models.IntegerField(default = 0)
    def __str__(self):
        return self.userid

index/forms.py
from django import forms
from . import models

class CreateItem(forms.ModelForm):
    class Meta:
        model = models.itemmodel
        fields = ('name', 'quantity', 'status','date',)

index/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse
from django.contrib.auth import login,logout
from .models import itemmodel
from django.contrib import messages
# Create your views here.
from django.contrib.auth.decorators import login_required
from . import forms
from datetime import datetime
def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('index:home')
    else:
        form = UserCreationForm()
    return render(request,'index/signuppage.html',{'form':form})
@login_required
def home(request,user_id):
    data =itemmodel.objects.filter(userid=user_id).order_by('date')
    # print(request)
    return render(request,'index/homepage.html', {"data" : data})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            current_user = request.user
            current_user = current_user.id
            return redirect('index:home',user_id = current_user)
    else:
        form = AuthenticationForm()
    return render(request,'index/loginpage.html',{'form':form})
def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect('index:login')
@login_required
def additem_view(request):
    print(request)
    if request.method == 'POST' :
        name = request.POST.get('name')
        quantity = request.POST.get('quantity')
        status = request.POST.get('status')
        date = request.POST.get('date')
        userid = request.user.id
        new = itemmodel(
              userid = userid,
              name = name,
              quantity = quantity,
              date = date,
              status = status,
        )
        new.save()
        messages.success(request,'Your order has been placed.')
        # return redirect('index:home',user_id = userid)
    return render(request,'index/additem.html')
@login_required
def update_view(request,item_id):
    data= itemmodel.objects.get(id=item_id)
    form = forms.CreateItem(request.POST)
    if form.is_valid():
            instance = form.save(commit=False)
            instance.userid = request.user.id
            # print(instance.status)
            instance.save()
            data.delete()
            return redirect('index:home',user_id = request.user.id)
    print(form.is_valid())
    return render(request,'index/update.html',{'data':data})

def filter_view(request):
    # print(request.POST)
    id=request.POST.get('date')
    print(id)
    if id:
        data = itemmodel.objects.filter(date=id,userid = request.user.id)
        return render(request, 'index/homepage.html' , {"data" : data})
    else :
        return redirect('index:home',user_id = request.user.id)
def delete_view(request,item_id):
    data = itemmodel.objects.get(id=item_id)
    data.delete()
    return redirect('index:home',user_id=request.user.id)
def edit(request,item_id):
    data= itemmodel.objects.get(id=item_id)
    print(data.date)
    data.date = data.date.strftime("%Y-%m-%d")
    print(data.date)
    return render(request, 'index/update.html', { 'data': data })

index/templates/index/additem.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Add List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
        <div class="container mt-5">
            <h1>Add Grocery List</h1>
            <form method="post">
               {%csrf_token%}
                <div class="form-group">
                    <label>Item name</label>
                    <input type="text" name="name" class="form-control" placeholder="Item name"/>
                </div>
                <div class="form-group">
                    <label>Item quantity</label>
                    <input type="text" name="quantity" class="form-control" placeholder="Item quantity"/>
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    <select name= "status" class="form-control">
                        <option value="0">PENDING</option>
                        <option value="1">BOUGHT</option>
                        <option value="2">NOT AVAILABLE</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" name="date" class="form-control" placeholder="Date">
                </div>
                <div class="form-group">
                  {% if messages %}
                  <ul class="messages">
                    {% for message in messages %}
                    <li  {% if message.tags %} class="text-info" {% endif %}> {{ message }} </li>
                    {% endfor %}
                  </ul>
                  {% endif %}
                </div>
                <div class="form-group">

                    <a href="{%url 'index:additem'%}"><input type="submit" value="Add" class="btn btn-danger"></a>
                    <a href="{%url 'index:home' request.user.id%}"><input type="button" class="btn btn-Success" value="HomePage"></a>
                </div>

            </form>
        </div>
    </body>
</html>

index/templates/index/homepage.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>View List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
        <div class="container mt-5">
            <!-- top -->
            <div class="row">
                <div class="col-lg-6">
                    <h1>View Grocery List</h1>
                </div>

                <div class="col-lg-6 float-right">
                  <form class="site-form" action="{% url 'index:filter' %}" method="post">
                     {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-8">
                            <!-- Date Filtering-->
                            <!-- <label for="date"></label> -->
                            <input id="date" name="date" type="date" class="form-control">
                        </div>
                        <div class="col-lg-4">
                            <input type="submit" class="btn btn-danger" value="filter">
                            <a href="{%url 'index:home' request.user.id%}"><input type="button" class="btn btn-Success" value="Reset"></a>
                        </div>
                    </div>
                    </form>
                    <div class="col-lg-4" style="margin-left:630px; margin-top:-55px;" >
                        <a href="{%url 'index:logout'%}"><input type="button" class="btn btn-danger" value="Logout"></a>
                    </div>
                </div>
            </div>
            <!-- // top -->
            <!-- Grocery Cards -->

            <div class="col-lg-4">
                <a href="{%url 'index:additem'%}"><input type="button" class="btn btn-primary" value="Add item"></a>

            </div>
            <div class="row mt-4">
                <!--- -->
                <!-- Loop This -->
                {% for d in data %}
                  <div class="col-lg-4" style="margin-bottom: 30px;">
                    <h5>{{d.date}}</h5>
                      <div class="card">
                          <div class="card-body">
                            <h5 class="card-title">{{d.name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{d.quantity}}</h6>
                            <!-- {{d.status}} -->
                            {% if d.status == 1%}
                            <p class="text-success">BOUGHT</p>
                            {% elif d.status == 0%}
                            <p class="text-info">PENDING</p>
                            {% else %}
                            <p class="text-danger">NOT AVAILABLE</p>
                            {% endif %}
                              <p><a href="{%url 'index:edit' d.id%}" class="text-info">Update</a>&emsp;&emsp;<a href="{%url 'index:delete' d.id%}" class="text-info">Delete</a></p>
                          </div>
                        </div>
                  </div>
                  {% endfor %}
            </div>
        </div>
    </body>
</html>

index/templates/index/loginpage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Login</h1>
    <form class="site-form" action="{%url 'index:login'%}" method="post">
      {%csrf_token%}
      {{form}}
      <input type="Submit" value="login">
    </form>
    <p>New to Service? Dont Worry!! <a href="{% url 'index:signup' %}">Sign Up</a></p>
  </body>
</html>

index/templates/index/signuppage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>SignUp</h1>
    <form class="site-form" action="/info/signup/" method="post">
      {%csrf_token%}
      {{form}}
      <input type="Submit" value="SignUp">
    </form>
  </body>
</html>

index/templates/index/update.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
        <div class="container mt-5">
            <h1>Update Grocery List</h1>
            <form  action="{%url 'index:updateitem' data.id%}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Item name</label>
                    <input id="name" name="name" type="text" class="form-control" placeholder="Item name" value="{{ data.name }}"/>
                </div>
                <div class="form-group">
                    <label for="quantity">Item quantity</label>
                    <input id="quantity" name="quantity" type="text" class="form-control" placeholder="Item quantity" value="{{ data.quantity }}"/>
                </div>
                <div class="form-group">
                    <label for="status">Item status</label>
                    <select id="status" name="status" class="form-control" value="{{ data.status }}">
                    
                       {% if data.status == 0%}
                       <option value="0" selected>PENDING</option>
                       <option value="1">BOUGHT</option>
                       <option value="2">NOT AVAILABLE</option>
                       {% elif data.status == 1%}
                       <option value="0">PENDING</option>
                       <option value="1" selected>BOUGHT</option>
                       <option value="2">NOT AVAILABLE</option>
                       {% else %}
                       <option value="0">PENDING</option>
                       <option value="1">BOUGHT</option>
                       <option value="2" selected>NOT AVAILABLE</option>
                       {% endif %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="date">Date</label>
                    <input id="date" name="date" type="date" class="form-control" placeholder="Date" value="{{ data.date }}">
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-danger">
                    <a href="{%url 'index:home' request.user.id%}"><input type="button" class="btn btn-Success" value="HomePage"></a>
                </div>
            </form>
        </div>
    </body>
</html>